### ISSUE TITLE
Bug: Module ist nicht installierbar in OXID v6.3.

### ISSUE THREAD

**Issue by TumTum** [Endereco/endereco-oxid6-client#13]
In der OXID v6.3 wird  guzzlehttp/guzzle 7.3.0 genutzt.

Problem 1
    - oxid-eshop/oxideshop-metapackage-ce is locked to version v6.3.0 and an update of this package was not requested.
    - endereco/endereco-oxid6-client 4.2.1 requires guzzlehttp/guzzle ^6.3 -> satisfiable by guzzlehttp/guzzle[6.3.0, ..., 6.5.5].
    - You can only install one version of a package, so only one of these can be installed: guzzlehttp/guzzle[v1.0.3, v1.0.4, v2.0.0, ..., v2.8.8, v3.0.0, ..., v3.8.1, 4.0.0-rc.1, ..., 4.2.4, 5.0.0, ..., 5.3.4, 6.0.0, ..., 6.5.5, 7.0.0-rc.1, ..., 7.3.0].

**Comment by iljamobilemojo** [comment]
@TumTum wann plant ihr den Umstieg auf 6.3?

**Comment by TumTum** [comment]
Zum Wechsel stehen uns zwei Module im Weg. eines von OXID die wollen es diese Woche beheben und eueres. Sobald die fertig sind geht das Update los.
Jedoch der nächste Slot fürs Update wäre Mitte Juli

**Comment by Endereco** [comment]
Ein Fix steht bereit, wartet aktuell auf Review und ausführliche Tests: https://github.com/Endereco/endereco-oxid6-client/commit/063b2b2db19efef4f252a4dca10b6c079cd2f874

Schnelltest in Oxid 6.3, MySQL 5.7, PHP 8.0 war aber erfolgreich.
